### ISSUE TITLE
Tests are unreadable because of the amount of warning due to parsing

### ISSUE THREAD

**Issue by PonteIneptique** [Capitains/Nautilus#60]
The current logs on Nautilus tests make reading impossible.
Warning should be removed in the test

**Comment by PonteIneptique** [comment]
```
======================================================================
ERROR: test_get_single_text_abort (tests.test_controller.NemoTestControllers)
Check that texts are filtered
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/Capitains/flask-capitains-nemo/tests/test_controller.py", line 131, in test_get_single_text_abort
    texts = self.nemo.get_collection("urn:cts:greekLIT:TLG0003:tlg001:perseus-grc132")
  File "/home/travis/build/Capitains/flask-capitains-nemo/flask_nemo/__init__.py", line 363, in get_collection
    return self.inventory[objectId]
  File "/home/travis/build/Capitains/flask-capitains-nemo/flask_nemo/__init__.py", line 261, in inventory
    return self.get_inventory()
  File "/home/travis/build/Capitains/flask-capitains-nemo/flask_nemo/__init__.py", line 352, in get_inventory
    self._inventory = self.resolver.getMetadata()
  File "/home/travis/virtualenv/python3.4.5/lib/python3.4/site-packages/MyCapytain/resolvers/cts/api.py", line 109, in getMetadata
    ti = XmlCtsTextInventoryMetadata.parse(self.endpoint.getCapabilities(**filters))
  File "/home/travis/virtualenv/python3.4.5/lib/python3.4/site-packages/MyCapytain/retrievers/cts5.py", line 67, in getCapabilities
    "request": "GetCapabilities"
  File "/home/travis/virtualenv/python3.4.5/lib/python3.4/site-packages/MyCapytain/retrievers/cts5.py", line 50, in call
    request.raise_for_status()
AttributeError: 'RequestPatch' object has no attribute 'raise_for_status'
```

**Comment by PonteIneptique** [comment]
Most logs are happening in test_fask_ext

**Comment by PonteIneptique** [comment]
Fixed by https://github.com/Capitains/Nautilus/commit/34eb3fbc4ee5515c1a5d3288eba06a14ea5e5568
