### ISSUE TITLE
capitains_nautilus/collections/sparql.py can't import GRAPH_BINDINGS

### ISSUE THREAD

**Issue by sonofmun** [Capitains/Nautilus#72]
After installing Nautilus with `python setup.py develop`, it throws an error the following error when trying to start with `capitains-nautilus --debug ~/results/CapiTainS_input/`. It looks like when you install Nautilus like this, it refers to the `dev` branch of MyCapytain, where GRAPH_BINDINGS exists. If I install with `pip install capitains-nautilus`, it works fine. Perhaps setup.py should install MyCapytain from its dev branch?

```
Traceback (most recent call last):
  File "/home/matt/envs/nautilus/bin/capitains-nautilus", line 11, in <module>
    load_entry_point('capitains-nautilus', 'console_scripts', 'capitains-nautilus')()
  File "/home/matt/envs/nautilus/lib/python3.6/site-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/matt/envs/nautilus/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/home/matt/envs/nautilus/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/home/matt/envs/nautilus/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/matt/Nautilus/capitains_nautilus/cmd.py", line 4, in <module>
    from capitains_nautilus.cts.resolver import NautilusCTSResolver
  File "/home/matt/Nautilus/capitains_nautilus/cts/resolver.py", line 15, in <module>
    from capitains_nautilus.collections.sparql import generate_alchemy_graph, clear_graph
  File "/home/matt/Nautilus/capitains_nautilus/collections/sparql.py", line 1, in <module>
    from MyCapytain.common.constants import RDF_NAMESPACES, get_graph, set_graph, GRAPH_BINDINGS
ImportError: cannot import name 'GRAPH_BINDINGS'
```

**Comment by PonteIneptique** [comment]
Right now, the only way is pip install - r requirements then python setup
develop

Le ven. 13 avr. 2018 à 5:15 PM, Matthew Munson <notifications@github.com> a
écrit :

**Comment by sonofmun** [comment]
Tried this and still gives the same error. From the Nautilus directory, dev branch:

```
pip install -r requirements.txt
python setup.py develop
```
This still installs MyCapytain 2.0.6, which doesn't have GRAPH_BINDINGS.
If I then do `pip install git+https://github.com/Capitains/MyCapytain@dev`, then it works.

**Comment by PonteIneptique** [comment]
Did you already have the env set up? If so, you had to run - - upgrade - -
no cache for requirements.txt

Le ven. 13 avr. 2018 à 6:30 PM, Matthew Munson <notifications@github.com> a
écrit :
